#!/bin/bash

# 全局配置 ---  global config --------------------------start

# 是否导入hadoop的jar包
IF_USE_HADOOP=false
# 是否导入hbase的jar包
IF_USE_HBASE=true

# hadoop 安装路径
export HADOOP_HOME="/usr/local/hadoop-3.2.1"
# 初始化CLASSPATH 一般为空就行
export CLASSPATH=""
# hadoop 版本
export HADOOP_VERSION="3.2.1"

# hbase 安装路径
export HBASE_HOME="/usr/local/hbase"

# 全局配置 ---  global config --------------------------end

# echo $IF_USE_HADOOP
if [[ $IF_USE_HADOOP == true ]];
then
echo 正在配置HADOOP...
export CLASSPATH=$($HADOOP_HOME/bin/hadoop classpath):$CLASSPATH
export CLASSPATH=$CLASSPATH:".:$JAVA_HOME/lib/tools.jar:$JAVA_HOME/lib/dt.jar"
export CLASSPATH=$CLASSPATH:"${HADOOP_HOME}/share/hadoop/common/hadoop-common-${HADOOP_VERSION}.jar"
export CLASSPATH=$CLASSPATH:"${HADOOP_HOME}/share/hadoop/common/hadoop-nfs-${HADOOP_VERSION}.jar"

for jar in ${HADOOP_HOME}/share/hadoop/common/lib/*.jar; do
    export CLASSPATH=$CLASSPATH:$jar
done

for jar in ${HADOOP_HOME}/share/hadoop/hdfs/lib/*.jar; do
    export CLASSPATH=$CLASSPATH:$jar
done

export CLASSPATH=$CLASSPATH:"${HADOOP_HOME}/share/hadoop/hdfs/haoop-hdfs-${HADOOP_VERSION}.jar"
export CLASSPATH=$CLASSPATH:"${HADOOP_HOME}/share/hadoop/hdfs/haoop-hdfs-nfs-${HADOOP_VERSION}.jar"
export CLASSPATH=$CLASSPATH:"${HADOOP_HOME}/share/hadoop/hdfs/hadoop-hdfs-client-${HADOOP_VERSION}.jar"
for jar in ${HADOOP_HOME}/share/hadoop/mapreduce/*.jar; do
    export CLASSPATH=$CLASSPATH:$jar
done
else 
    echo IF_USE_HADOOP=false
fi

if [[ $IF_USE_HBASE = true ]];
then
echo 正在配置HBASE...
for jar in ${HBASE_HOME}/lib/*.jar; do
    export CLASSPATH=$CLASSPATH:$jar
done
for jar in ${HBASE_HOME}/lib/client-facing-thirdparty/*.jar; do
    export CLASSPATH=$CLASSPATH:$jar
done
for jar in ${HBASE_HOME}/lib/shaded-clients/*.jar; do
    export CLASSPATH=$CLASSPATH:$jar
done
for jar in ${HBASE_HOME}/lib/jdk11/*.jar; do
    export CLASSPATH=$CLASSPATH:$jar
done
else 
    echo IF_USE_HBASE=false
fi
# echo $CLASSPATH
echo 配置环境完成!
echo 正在编译java程序...
javac $1".java"
echo 编译java程序完成!
echo 启动java程序...
java $1
